# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

[
  {
    "Constellation": "Andromeda",
    "Abbr": "And",
    "Meaning": "The Daughter of Cassiopeia",
    "Pronunciation": "an-drom-E-du",
    "Genitive": "Andromedae",
    "Area(sq°)": 722.278,
    "S": 3,
    "Date": 10.04,
    "V": "V"
  },
  {
    "Constellation": "Antlia",
    "Abbr": "Ant",
    "Meaning": "The Air Pump",
    "Pronunciation": "ant-lE-u",
    "Genitive": "Antliae",
    "Area(sq°)": 238.901,
    "S": "",
    "Date": 2.25,
    "V": "P"
  },
  {
    "Constellation": "Apus",
    "Abbr": "Aps",
    "Meaning": "The Bird of Paradise",
    "Pronunciation": "A-pus",
    "Genitive": "Apodis",
    "Area(sq°)": 206.327,
    "S": "",
    "Date": 5.25,
    "V": "N"
  },
  {
    "Constellation": "Aquarius",
    "Abbr": "Aqr",
    "Meaning": "The Water-bearer",
    "Pronunciation": "u-kwer-E-us",
    "Genitive": "Aquarii",
    "Area(sq°)": 979.854,
    "S": "",
    "Date": 8.27,
    "V": "V"
  },
  {
    "Constellation": "Aquila",
    "Abbr": "Aql",
    "Meaning": "The Eagle",
    "Pronunciation": "u-kwil-u or ak-wil-u",
    "Genitive": "Aquilae",
    "Area(sq°)": 652.473,
    "S": 1,
    "Date": 7.18,
    "V": "V"
  },
  {
    "Constellation": "Ara",
    "Abbr": "Ara",
    "Meaning": "The Altar",
    "Pronunciation": "A-ru",
    "Genitive": "Arae",
    "Area(sq°)": 237.057,
    "S": "",
    "Date": 6.13,
    "V": "N"
  },
  {
    "Constellation": "Aries",
    "Abbr": "Ari",
    "Meaning": "The Ram",
    "Pronunciation": "e-rEz or e-ri-Ez",
    "Genitive": "Arietis",
    "Area(sq°)": 441.395,
    "S": 1,
    "Date": 11.01,
    "V": "V"
  },
  {
    "Constellation": "Auriga",
    "Abbr": "Aur",
    "Meaning": "The Charioteer",
    "Pronunciation": "o-rI-gu or o-rE-gu",
    "Genitive": "Aurigae",
    "Area(sq°)": 657.438,
    "S": 2,
    "Date": 12.23,
    "V": "V"
  },
  {
    "Constellation": "Bootes",
    "Abbr": "Boo",
    "Meaning": "The Herdsman",
    "Pronunciation": "bO-O-tEz",
    "Genitive": "Bootis",
    "Area(sq°)": 906.831,
    "S": 2,
    "Date": 5.03,
    "V": "V"
  },
  {
    "Constellation": "Caelum",
    "Abbr": "Cae",
    "Meaning": "The Chisel",
    "Pronunciation": "sE-lum",
    "Genitive": "Caeli",
    "Area(sq°)": 124.865,
    "S": "",
    "Date": 12.02,
    "V": "P"
  },
  {
    "Constellation": "Camelopardalis",
    "Abbr": "Cam",
    "Meaning": "The Giraffe",
    "Pronunciation": "ka-mel-O-por-du-lis",
    "Genitive": "Camelopardalis",
    "Area(sq°)": 756.828,
    "S": "",
    "Date": 2.03,
    "V": "V"
  },
  {
    "Constellation": "Cancer",
    "Abbr": "Cnc",
    "Meaning": "The Crab",
    "Pronunciation": "kan-ser",
    "Genitive": "Cancri",
    "Area(sq°)": 505.872,
    "S": "",
    "Date": 1.31,
    "V": "V"
  },
  {
    "Constellation": "Canes Venatici",
    "Abbr": "CVn",
    "Meaning": "The Hunting Dogs",
    "Pronunciation": "kA-nEz vE-nat-i-sI",
    "Genitive": "Canum Venaticorum",
    "Area(sq°)": 465.194,
    "S": "",
    "Date": 4.09,
    "V": "V"
  },
  {
    "Constellation": "Canis Major",
    "Abbr": "CMa",
    "Meaning": "The Big Dog",
    "Pronunciation": "kA-nis mA-jer",
    "Genitive": "Canis Majoris",
    "Area(sq°)": 380.118,
    "S": 5,
    "Date": 1.03,
    "V": "V"
  },
  {
    "Constellation": "Canis Minor",
    "Abbr": "CMi",
    "Meaning": "The Little Dog",
    "Pronunciation": "kA-nis mI-ner",
    "Genitive": "Canis Minoris",
    "Area(sq°)": 183.367,
    "S": 1,
    "Date": 1.16,
    "V": "V"
  },
  {
    "Constellation": "Capricornus",
    "Abbr": "Cap",
    "Meaning": "The Goat",
    "Pronunciation": "kap-ri-kor-nus",
    "Genitive": "Capricorni",
    "Area(sq°)": 413.947,
    "S": "",
    "Date": 8.08,
    "V": "V"
  },
  {
    "Constellation": "Carina",
    "Abbr": "Car",
    "Meaning": "The Keel",
    "Pronunciation": "ku-rI-nu or ku-rE-nu",
    "Genitive": "Carinae",
    "Area(sq°)": 494.184,
    "S": 4,
    "Date": 2.01,
    "V": "N"
  },
  {
    "Constellation": "Cassiopeia",
    "Abbr": "Cas",
    "Meaning": "The Queen",
    "Pronunciation": "kas-E-O-pE-yu",
    "Genitive": "Cassiopeiae",
    "Area(sq°)": 598.407,
    "S": 3,
    "Date": 10.12,
    "V": "V"
  },
  {
    "Constellation": "Centaurus",
    "Abbr": "Cen",
    "Meaning": "The Centaur",
    "Pronunciation": "sen-tor-us",
    "Genitive": "Centauri",
    "Area(sq°)": 1060.422,
    "S": 9,
    "Date": 4.08,
    "V": "P"
  },
  {
    "Constellation": "Cepheus",
    "Abbr": "Cep",
    "Meaning": "The King",
    "Pronunciation": "sE-fE-us or sE-fUs",
    "Genitive": "Cephei",
    "Area(sq°)": 587.787,
    "S": 1,
    "Date": 10.3,
    "V": "V"
  },
  {
    "Constellation": "Cetus",
    "Abbr": "Cet",
    "Meaning": "The Whale",
    "Pronunciation": "sE-tus",
    "Genitive": "Ceti",
    "Area(sq°)": 1231.411,
    "S": 2,
    "Date": 10.17,
    "V": "V"
  },
  {
    "Constellation": "Chamaeleon",
    "Abbr": "Cha",
    "Meaning": "The Chameleon",
    "Pronunciation": "ku-mE-lE-un",
    "Genitive": "Chamaeleontis",
    "Area(sq°)": 131.592,
    "S": "",
    "Date": 3.03,
    "V": "N"
  },
  {
    "Constellation": "Circinus",
    "Abbr": "Cir",
    "Meaning": "The Compasses",
    "Pronunciation": "ser-sin-us",
    "Genitive": "Circini",
    "Area(sq°)": 93.353,
    "S": "",
    "Date": 5.01,
    "V": "N"
  },
  {
    "Constellation": "Columba",
    "Abbr": "Col",
    "Meaning": "The Dove",
    "Pronunciation": "kO-lum-bu",
    "Genitive": "Columbae",
    "Area(sq°)": 270.184,
    "S": "",
    "Date": 12.2,
    "V": "P"
  },
  {
    "Constellation": "Coma Berenices",
    "Abbr": "Com",
    "Meaning": "Berenice's Hair",
    "Pronunciation": "kO-mu ber-e-nI-sEz",
    "Genitive": "Comae Berenices",
    "Area(sq°)": 386.475,
    "S": "",
    "Date": 4.04,
    "V": "V"
  },
  {
    "Constellation": "Corona Australis",
    "Abbr": "CrA",
    "Meaning": "The Southern Crown",
    "Pronunciation": "kO-rO-nu aus-trA-lis",
    "Genitive": "Coronae Australis",
    "Area(sq°)": 127.696,
    "S": "",
    "Date": 7.02,
    "V": "P"
  },
  {
    "Constellation": "Corona Borealis",
    "Abbr": "CrB",
    "Meaning": "The Northern Crown",
    "Pronunciation": "kO-rO-nu bOr-E-al-is",
    "Genitive": "Coronae Borealis",
    "Area(sq°)": 178.71,
    "S": 1,
    "Date": 5.2,
    "V": "V"
  },
  {
    "Constellation": "Corvus",
    "Abbr": "Crv",
    "Meaning": "The Crow",
    "Pronunciation": "kor-vus",
    "Genitive": "Corvi",
    "Area(sq°)": 183.801,
    "S": "",
    "Date": 3.3,
    "V": "V"
  },
  {
    "Constellation": "Crater",
    "Abbr": "Crt",
    "Meaning": "The Cup",
    "Pronunciation": "krA-ter",
    "Genitive": "Crateris",
    "Area(sq°)": 282.398,
    "S": "",
    "Date": 3.14,
    "V": "V"
  },
  {
    "Constellation": "Crux",
    "Abbr": "Cru",
    "Meaning": "The Cross",
    "Pronunciation": "kruks",
    "Genitive": "Crucis",
    "Area(sq°)": 68.447,
    "S": 3,
    "Date": 3.3,
    "V": "N"
  },
  {
    "Constellation": "Cygnus",
    "Abbr": "Cyg",
    "Meaning": "The Swan",
    "Pronunciation": "sig-nus",
    "Genitive": "Cygni",
    "Area(sq°)": 803.983,
    "S": 3,
    "Date": 8.01,
    "V": "V"
  },
  {
    "Constellation": "Delphinus",
    "Abbr": "Del",
    "Meaning": "The Dolphin",
    "Pronunciation": "del-fI-nus",
    "Genitive": "Delphini",
    "Area(sq°)": 188.549,
    "S": "",
    "Date": 8.02,
    "V": "V"
  },
  {
    "Constellation": "Dorado",
    "Abbr": "Dor",
    "Meaning": "The Swordfish",
    "Pronunciation": "dO-ro-dO",
    "Genitive": "Doradus",
    "Area(sq°)": 179.173,
    "S": "",
    "Date": 12.1,
    "V": "N"
  },
  {
    "Constellation": "Draco",
    "Abbr": "Dra",
    "Meaning": "The Dragon",
    "Pronunciation": "drA-kO",
    "Genitive": "Draconis",
    "Area(sq°)": 1082.952,
    "S": 1,
    "Date": 5.1,
    "V": "V"
  },
  {
    "Constellation": "Equuleus",
    "Abbr": "Equ",
    "Meaning": "The Little Horse",
    "Pronunciation": "E-kwoo-lE-us",
    "Genitive": "Equulei",
    "Area(sq°)": 71.641,
    "S": "",
    "Date": 8.1,
    "V": "V"
  },
  {
    "Constellation": "Eridanus",
    "Abbr": "Eri",
    "Meaning": "The River",
    "Pronunciation": "E-rid-a-nus",
    "Genitive": "Eridani",
    "Area(sq°)": 1137.919,
    "S": 1,
    "Date": 11.11,
    "V": "P"
  },
  {
    "Constellation": "Fornax",
    "Abbr": "For",
    "Meaning": "The Furnace",
    "Pronunciation": "for-naks",
    "Genitive": "Fornacis",
    "Area(sq°)": 397.502,
    "S": "",
    "Date": 11.03,
    "V": "P"
  },
  {
    "Constellation": "Gemini",
    "Abbr": "Gem",
    "Meaning": "The Twins",
    "Pronunciation": "jem-i-nI",
    "Genitive": "Geminorum",
    "Area(sq°)": 513.761,
    "S": 3,
    "Date": 1.07,
    "V": "V"
  },
  {
    "Constellation": "Grus",
    "Abbr": "Gru",
    "Meaning": "The Crane",
    "Pronunciation": "grus",
    "Genitive": "Gruis",
    "Area(sq°)": 365.513,
    "S": 2,
    "Date": 8.29,
    "V": "P"
  },
  {
    "Constellation": "Hercules",
    "Abbr": "Her",
    "Meaning": "The Son of Zeus",
    "Pronunciation": "her-cU-lEz",
    "Genitive": "Herculis",
    "Area(sq°)": 1225.148,
    "S": "",
    "Date": 6.13,
    "V": "V"
  },
  {
    "Constellation": "Horologium",
    "Abbr": "Hor",
    "Meaning": "The Clock",
    "Pronunciation": "hor-O-lO-jE-um",
    "Genitive": "Horologii",
    "Area(sq°)": 248.885,
    "S": "",
    "Date": 11.1,
    "V": "N"
  },
  {
    "Constellation": "Hydra",
    "Abbr": "Hya",
    "Meaning": "The female Water Snake",
    "Pronunciation": "hId-ru",
    "Genitive": "Hydrae",
    "Area(sq°)": 1302.844,
    "S": 1,
    "Date": 3.17,
    "V": "V"
  },
  {
    "Constellation": "Hydrus",
    "Abbr": "Hyi",
    "Meaning": "The male Water Snake",
    "Pronunciation": "hId-rus",
    "Genitive": "Hydri",
    "Area(sq°)": 243.035,
    "S": "",
    "Date": 10.27,
    "V": "N"
  },
  {
    "Constellation": "Indus",
    "Abbr": "Ind",
    "Meaning": "The Indian",
    "Pronunciation": "in-dus",
    "Genitive": "Indi",
    "Area(sq°)": 294.006,
    "S": "",
    "Date": 8.22,
    "V": "N"
  },
  {
    "Constellation": "Lacerta",
    "Abbr": "Lac",
    "Meaning": "The Lizard",
    "Pronunciation": "lu-ser-tu",
    "Genitive": "Lacertae",
    "Area(sq°)": 200.688,
    "S": "",
    "Date": 8.29,
    "V": "V"
  },
  {
    "Constellation": "Leo",
    "Abbr": "Leo",
    "Meaning": "The Lion",
    "Pronunciation": "lE-O",
    "Genitive": "Leonis",
    "Area(sq°)": 946.964,
    "S": 4,
    "Date": 3.03,
    "V": "V"
  },
  {
    "Constellation": "Leo Minor",
    "Abbr": "LMi",
    "Meaning": "The Little Lion",
    "Pronunciation": "lE-O mI-ner",
    "Genitive": "Leonis Minoris",
    "Area(sq°)": 231.956,
    "S": "",
    "Date": 2.24,
    "V": "V"
  },
  {
    "Constellation": "Lepus",
    "Abbr": "Lep",
    "Meaning": "The Hare",
    "Pronunciation": "lE-pus",
    "Genitive": "Leporis",
    "Area(sq°)": 290.291,
    "S": 1,
    "Date": 12.15,
    "V": "V"
  },
  {
    "Constellation": "Libra",
    "Abbr": "Lib",
    "Meaning": "The Balance",
    "Pronunciation": "lE-bru or lI-bru",
    "Genitive": "Librae",
    "Area(sq°)": 538.052,
    "S": "",
    "Date": 5.11,
    "V": "V"
  },
  {
    "Constellation": "Lupus",
    "Abbr": "Lup",
    "Meaning": "The Wolf",
    "Pronunciation": "loo-pus",
    "Genitive": "Lupi",
    "Area(sq°)": 333.683,
    "S": 1,
    "Date": 5.11,
    "V": "P"
  },
  {
    "Constellation": "Lynx",
    "Abbr": "Lyn",
    "Meaning": "The Lynx",
    "Pronunciation": "links",
    "Genitive": "Lyncis",
    "Area(sq°)": 545.386,
    "S": "",
    "Date": 1.21,
    "V": "V"
  },
  {
    "Constellation": "Lyra",
    "Abbr": "Lyr",
    "Meaning": "The Lyre",
    "Pronunciation": "lI-ru",
    "Genitive": "Lyrae",
    "Area(sq°)": 286.476,
    "S": 1,
    "Date": 7.05,
    "V": "V"
  },
  {
    "Constellation": "Mensa",
    "Abbr": "Men",
    "Meaning": "The Table",
    "Pronunciation": "men-su",
    "Genitive": "Mensae",
    "Area(sq°)": 153.484,
    "S": "",
    "Date": 12.13,
    "V": "N"
  },
  {
    "Constellation": "Microscopium",
    "Abbr": "Mic",
    "Meaning": "The Microscope",
    "Pronunciation": "mI-krO-scO-pE-um",
    "Genitive": "Microscopii",
    "Area(sq°)": 209.513,
    "S": "",
    "Date": 8.06,
    "V": "P"
  },
  {
    "Constellation": "Monoceros",
    "Abbr": "Mon",
    "Meaning": "The Unicorn",
    "Pronunciation": "mO-nos-er-us",
    "Genitive": "Monocerotis",
    "Area(sq°)": 481.569,
    "S": "",
    "Date": 1.07,
    "V": "V"
  },
  {
    "Constellation": "Musca",
    "Abbr": "Mus",
    "Meaning": "The Fly",
    "Pronunciation": "mus-ku",
    "Genitive": "Muscae",
    "Area(sq°)": 138.355,
    "S": "",
    "Date": 4.01,
    "V": "N"
  },
  {
    "Constellation": "Norma",
    "Abbr": "Nor",
    "Meaning": "The sq°uare",
    "Pronunciation": "nor-mu",
    "Genitive": "Normae",
    "Area(sq°)": 165.29,
    "S": "",
    "Date": 5.21,
    "V": "N"
  },
  {
    "Constellation": "Octans",
    "Abbr": "Oct",
    "Meaning": "The Octant",
    "Pronunciation": "ok-tanz",
    "Genitive": "Octantis",
    "Area(sq°)": 291.045,
    "S": "",
    "Date": 9.06,
    "V": "N"
  },
  {
    "Constellation": "Ophiuchus",
    "Abbr": "Oph",
    "Meaning": "The Serpent-holder",
    "Pronunciation": "O-fE-U-kus",
    "Genitive": "Ophiuchi",
    "Area(sq°)": 948.34,
    "S": 3,
    "Date": 6.13,
    "V": "V"
  },
  {
    "Constellation": "Orion",
    "Abbr": "Ori",
    "Meaning": "The Hunter",
    "Pronunciation": "O-rI-un",
    "Genitive": "Orionis",
    "Area(sq°)": 594.12,
    "S": 7,
    "Date": 12.15,
    "V": "V"
  },
  {
    "Constellation": "Pavo",
    "Abbr": "Pav",
    "Meaning": "The Peacock",
    "Pronunciation": "pA-vO",
    "Genitive": "Pavonis",
    "Area(sq°)": 377.666,
    "S": 1,
    "Date": 7.17,
    "V": "N"
  },
  {
    "Constellation": "Pegasus",
    "Abbr": "Peg",
    "Meaning": "The Winged Horse",
    "Pronunciation": "peg-u-sus",
    "Genitive": "Pegasi",
    "Area(sq°)": 1120.794,
    "S": 3,
    "Date": 9.02,
    "V": "V"
  },
  {
    "Constellation": "Perseus",
    "Abbr": "Per",
    "Meaning": "The Rescuer of Andromeda",
    "Pronunciation": "per-sE-us or per-sus",
    "Genitive": "Persei",
    "Area(sq°)": 614.997,
    "S": 2,
    "Date": 11.09,
    "V": "V"
  },
  {
    "Constellation": "Phoenix",
    "Abbr": "Phe",
    "Meaning": "The Phoenix",
    "Pronunciation": "fE-niks",
    "Genitive": "Phoenicis",
    "Area(sq°)": 469.319,
    "S": 1,
    "Date": 10.06,
    "V": "N"
  },
  {
    "Constellation": "Pictor",
    "Abbr": "Pic",
    "Meaning": "The Painter",
    "Pronunciation": "pic-ter",
    "Genitive": "Pictoris",
    "Area(sq°)": 246.739,
    "S": "",
    "Date": 12.17,
    "V": "N"
  },
  {
    "Constellation": "Pisces",
    "Abbr": "Psc",
    "Meaning": "The Fishes",
    "Pronunciation": "pI-sEz",
    "Genitive": "Piscium",
    "Area(sq°)": 889.417,
    "S": "",
    "Date": 9.29,
    "V": "V"
  },
  {
    "Constellation": "Piscis Austrinus",
    "Abbr": "PsA",
    "Meaning": "The Southern Fish",
    "Pronunciation": "pI-sis aus-trI-nus",
    "Genitive": "Piscis Austrini",
    "Area(sq°)": 245.375,
    "S": 1,
    "Date": 8.26,
    "V": "V"
  },
  {
    "Constellation": "Puppis",
    "Abbr": "Pup",
    "Meaning": "The Stern",
    "Pronunciation": "pup-is",
    "Genitive": "Puppis",
    "Area(sq°)": 673.434,
    "S": 1,
    "Date": 1.1,
    "V": "P"
  },
  {
    "Constellation": "Pyxis",
    "Abbr": "Pyx",
    "Meaning": "The Compass",
    "Pronunciation": "pik-sis",
    "Genitive": "Pyxidis",
    "Area(sq°)": 220.833,
    "S": "",
    "Date": 2.05,
    "V": "V"
  },
  {
    "Constellation": "Reticulum",
    "Abbr": "Ret",
    "Meaning": "The Reticle",
    "Pronunciation": "rE-tik-U-lum",
    "Genitive": "Reticuli",
    "Area(sq°)": 113.936,
    "S": "",
    "Date": 11.2,
    "V": "N"
  },
  {
    "Constellation": "Sagitta",
    "Abbr": "Sge",
    "Meaning": "The Arrow",
    "Pronunciation": "su-jit-u",
    "Genitive": "Sagittae",
    "Area(sq°)": 79.932,
    "S": "",
    "Date": 7.17,
    "V": "V"
  },
  {
    "Constellation": "Sagittarius",
    "Abbr": "Sgr",
    "Meaning": "The Archer",
    "Pronunciation": "saj-i-ter-E-us",
    "Genitive": "Sagittarii",
    "Area(sq°)": 867.432,
    "S": 2,
    "Date": 7.09,
    "V": "P"
  },
  {
    "Constellation": "Scorpius",
    "Abbr": "Sco",
    "Meaning": "The Scorpion",
    "Pronunciation": "skor-pE-us",
    "Genitive": "Scorpii",
    "Area(sq°)": 496.783,
    "S": 7,
    "Date": 6.05,
    "V": "P"
  },
  {
    "Constellation": "Sculptor",
    "Abbr": "Scl",
    "Meaning": "The Sculptor",
    "Pronunciation": "skulp-ter",
    "Genitive": "Sculptoris",
    "Area(sq°)": 474.764,
    "S": "",
    "Date": 9.28,
    "V": "P"
  },
  {
    "Constellation": "Scutum",
    "Abbr": "Sct",
    "Meaning": "The Shield",
    "Pronunciation": "skU-tum",
    "Genitive": "Scuti",
    "Area(sq°)": 109.114,
    "S": "",
    "Date": 7.02,
    "V": "V"
  },
  {
    "Constellation": "Serpens (Caput)",
    "Abbr": "Ser",
    "Meaning": "The (Head of the) Serpent",
    "Pronunciation": "ser-penz",
    "Genitive": "Serpentis",
    "Area(sq°)": 428.484,
    "S": "",
    "Date": 5.19,
    "V": "V"
  },
  {
    "Constellation": "Serpens (Cauda)",
    "Abbr": "Ser",
    "Meaning": "The (Tail of the) Serpent",
    "Pronunciation": "ser-penz",
    "Genitive": "Serpentis",
    "Area(sq°)": 208.444,
    "S": "",
    "Date": 6.24,
    "V": "V"
  },
  {
    "Constellation": "Sextans",
    "Abbr": "Sex",
    "Meaning": "The Sextant",
    "Pronunciation": "seks-tuns",
    "Genitive": "Sextantis",
    "Area(sq°)": 313.515,
    "S": "",
    "Date": 2.25,
    "V": "V"
  },
  {
    "Constellation": "Taurus",
    "Abbr": "Tau",
    "Meaning": "The Bull",
    "Pronunciation": "tor-us",
    "Genitive": "Tauri",
    "Area(sq°)": 797.249,
    "S": 2,
    "Date": 12.02,
    "V": "V"
  },
  {
    "Constellation": "Telescopium",
    "Abbr": "Tel",
    "Meaning": "The Telescope",
    "Pronunciation": "tel-e-skO-pE-um",
    "Genitive": "Telescopii",
    "Area(sq°)": 251.512,
    "S": "",
    "Date": 7.12,
    "V": "N"
  },
  {
    "Constellation": "Triangulum",
    "Abbr": "Tri",
    "Meaning": "The Triangle",
    "Pronunciation": "trI-ang-gU-lum",
    "Genitive": "Trianguli",
    "Area(sq°)": 131.847,
    "S": "",
    "Date": 10.25,
    "V": "V"
  },
  {
    "Constellation": "Triangulum Australe",
    "Abbr": "TrA",
    "Meaning": "The Southern Triangle",
    "Pronunciation": "trI-ang-gU-lum aus-trA-lE",
    "Genitive": "Trainguli Australis",
    "Area(sq°)": 109.978,
    "S": 1,
    "Date": 5.24,
    "V": "N"
  },
  {
    "Constellation": "Tucana",
    "Abbr": "Tuc",
    "Meaning": "The Toucan",
    "Pronunciation": "too-kan-u or too-kA-nu",
    "Genitive": "Tucanae",
    "Area(sq°)": 294.557,
    "S": "",
    "Date": 9.18,
    "V": "N"
  },
  {
    "Constellation": "Ursa Major",
    "Abbr": "UMa",
    "Meaning": "The Great Bear",
    "Pronunciation": "Er-su mA-jer",
    "Genitive": "Ursae Majoris",
    "Area(sq°)": 1279.66,
    "S": 6,
    "Date": 3.12,
    "V": "V"
  },
  {
    "Constellation": "Ursa Minor",
    "Abbr": "UMi",
    "Meaning": "The Little Bear",
    "Pronunciation": "Er-su mI-ner",
    "Genitive": "Ursae Minoris",
    "Area(sq°)": 255.864,
    "S": 2,
    "Date": 5.08,
    "V": "V"
  },
  {
    "Constellation": "Vela",
    "Abbr": "Vel",
    "Meaning": "The Sails",
    "Pronunciation": "vE-lu",
    "Genitive": "Velorum",
    "Area(sq°)": 499.649,
    "S": 4,
    "Date": 2.14,
    "V": "P"
  },
  {
    "Constellation": "Virgo",
    "Abbr": "Vir",
    "Meaning": "The Maiden",
    "Pronunciation": "ver-gO",
    "Genitive": "Virginis",
    "Area(sq°)": 1294.428,
    "S": 1,
    "Date": 4.13,
    "V": "V"
  },
  {
    "Constellation": "Volans",
    "Abbr": "Vol",
    "Meaning": "The Flying Fish",
    "Pronunciation": "vO-lanz",
    "Genitive": "Volantis",
    "Area(sq°)": 141.354,
    "S": "",
    "Date": 1.18,
    "V": "N"
  },
  {
    "Constellation": "Vulpecula",
    "Abbr": "Vul",
    "Meaning": "The Fox",
    "Pronunciation": "vul-pek-U-lu",
    "Genitive": "Vulpeculae",
    "Area(sq°)": 268.165,
    "S": "",
    "Date": 7.26,
    "V": "V"
  }
]